name: Security Pipeline (OWASP Top 10 Coverage)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Weekly Monday 02:00 UTC scan

jobs:
  sast:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3

  dependency_scan:
    name: Dependency Audit (A06)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm Audit
        run: npm audit --audit-level=high || true

  iac_scan:
    name: IaC & Config Scan (A05)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

  dast:
    name: Dynamic Analysis (DAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'https://philipghering.nl'

  secrets_scan:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2

  # container_scan:
  #   name: Container Image Scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Scan with Trivy
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: your-image:latest
